In [2]:
# importando as bibliotecas
import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D

In [3]:
# Gerando os dados para as ações
np.random.seed(0)
n_samples=100
symbols = ['AAPL','GOOGLE','MSFT','AMZN','TSLA','FB']
prices = np.random.uniform(50,4000,n_samples)
volume = np.random.randint(100000,500000,n_samples)
market_cap = np.random.uniform(1e10,2e12,n_samples)

In [4]:
data = pd.DataFrame({
    'Simbolo':np.random.choice(symbols,n_samples),
    'Preços':prices,
    'Volume':volume,
    'Capitalização de mercado':market_cap
})

In [5]:
data.head()

  Simbolo       Preços  Volume  Capitalização de mercado
0      FB  2217.813341  452893              8.459500e+11
1  GOOGLE  2874.997997  264610              1.106703e+11
2    AAPL  2430.915335  108286              7.373373e+11
3      FB  2202.288573  471938              4.308967e+10
4    AAPL  1723.436457  204299              4.691772e+11

In [6]:
# Realizando o agrupamento com kmeans
data_n = pd.get_dummies(data,columns=['Simbolo'],drop_first=True)

In [7]:
data_n

,Preços,Volume,Capitalização de mercado,Simbolo_AMZN,Simbolo_FB,Simbolo_GOOGLE,Simbolo_MSFT,Simbolo_TSLA
0,2217.813341,452893,8.459500e+11,False,True,False,False,False
1,2874.997997,264610,1.106703e+11,False,False,True,False,False
2,2430.915335,108286,7.373373e+11,False,False,False,False,False
3,2202.288573,471938,4.308967e+10,False,True,False,False,False
4,1723.436457,204299,4.691772e+11,False,False,False,False,False
...,...,...,...,...,...,...,...,...
95,773.605880,182727,1.466071e+12,False,False,False,False,False
96,2366.726092,422953,1.007731e+11,False,True,False,False,False
97,129.424807,233193,4.262225e+11,True,False,False,False,False
98,3324.313115,276425,5.809609e+11,False,False,True,False,False
99,68.547131,321059,1.357754e+12,False,True,False,False,False